import { Task } from './types';

export const dummyTasks: Task[] = [
  {
    id: 1,
    title: 'Setup GitHub Repository',
    status: 'todo',
    createdAt: '2025-07-01T09:00:00.000Z',
    updatedAt: '2025-07-01T09:00:00.000Z',
    description: 'Create and configure the GitHub repo with branch protection rules.',
    assignee: 'Prasant Mahato',
    reporter: 'Anjali Sharma',
    labels: ['setup', 'git'],
    order: 1,
    comments: [{ text: 'Don’t forget to add the README file.', time: '2025-07-01T10:00:00.000Z' }],
    sprintNo: 'Sprint 1',
    projectNo: 'PRJ-001',
    acceptanceCriteria: 'Repo must have README, CONTRIBUTING, and .gitignore.',
    taskType: 'Ticket',
  },
  {
    id: 2,
    title: 'Design Login Page',
    status: 'inprogress',
    createdAt: '2025-07-02T10:30:00.000Z',
    updatedAt: '2025-07-03T12:00:00.000Z',
    description: 'UI for login with email and password using Tailwind CSS.',
    assignee: 'Sneha Raj',
    reporter: 'Prasant Mahato',
    labels: ['frontend', 'UI'],
    order: 2,
    comments: [{ text: 'Add forgot password link.', time: '2025-07-03T13:00:00.000Z' }],
    sprintNo: 'Sprint 1',
    projectNo: 'PRJ-001',
    acceptanceCriteria: 'Login form with validation and responsiveness.',
    taskType: 'Ticket',
  },
  {
    id: 3,
    title: 'Fix API Bug in authentication flow',
    status: 'review',
    createdAt: '2025-07-02T15:00:00.000Z',
    updatedAt: '2025-07-04T08:30:00.000Z',
    description: 'Fixes login failure due to incorrect token parsing.',
    assignee: 'Anjali Sharma',
    reporter: 'Rahul Mehta',
    labels: ['Bug', 'backend'],
    order: 3,
    comments: [{ text: 'Works fine on staging.', time: '2025-07-04T09:00:00.000Z' }],
    sprintNo: 'Sprint 1',
    projectNo: 'PRJ-001',
    acceptanceCriteria: 'Valid login returns correct token.',
    taskType: 'Bug',
  },
  {
    id: 4,
    title: 'Implement Task Card Component',
    status: 'done',
    createdAt: '2025-07-01T12:00:00.000Z',
    updatedAt: '2025-07-05T11:00:00.000Z',
    description: 'Card UI for displaying task title, status and assignee.',
    assignee: 'Kiran Patil',
    reporter: 'Sneha Raj',
    labels: ['react', 'component'],
    order: 4,
    comments: [{ text: 'Looks neat!', time: '2025-07-05T12:00:00.000Z' }],
    sprintNo: 'Sprint 1',
    projectNo: 'PRJ-001',
    acceptanceCriteria: 'Reusable and responsive card component.',
    taskType: 'Ticket',
  },
  {
    id: 5,
    title: 'Write Unit Tests for Task Reducer',
    status: 'inprogress',
    createdAt: '2025-07-03T09:00:00.000Z',
    updatedAt: '2025-07-05T10:00:00.000Z',
    description: 'Add Jest tests for create/update/delete reducers.',
    assignee: 'Prasant Mahato',
    reporter: 'Anjali Sharma',
    labels: ['testing', 'redux'],
    order: 5,
    comments: [{ text: 'Use mock store for testing.', time: '2025-07-05T11:00:00.000Z' }],
    sprintNo: 'Sprint 2',
    projectNo: 'PRJ-001',
    acceptanceCriteria: '100% coverage on reducers.',
    taskType: 'Ticket',
  },
  {
    id: 6,
    title: 'Create Sprint Dashboard',
    status: 'todo',
    createdAt: '2025-07-06T10:00:00.000Z',
    updatedAt: '2025-07-06T10:00:00.000Z',
    description: 'Summary dashboard with burndown and task status chart.',
    assignee: 'Rahul Mehta',
    reporter: 'Sneha Raj',
    labels: ['dashboard', 'analytics'],
    order: 6,
    comments: [],
    sprintNo: 'Sprint 2',
    projectNo: 'PRJ-001',
    acceptanceCriteria: 'Show visual burndown and task stats.',
    taskType: 'Spike',
  },
  {
    id: 7,
    title: 'Optimize Database Indexes',
    status: 'review',
    createdAt: '2025-07-04T11:00:00.000Z',
    updatedAt: '2025-07-06T14:00:00.000Z',
    description: 'Analyze slow queries and add indexes where necessary.',
    assignee: 'Sneha Raj',
    reporter: 'Kiran Patil',
    labels: ['database', 'performance'],
    order: 7,
    comments: [{ text: 'Indexed `user_id` and `task_id` fields.', time: '2025-07-06T14:10:00.000Z' }],
    sprintNo: 'Sprint 2',
    projectNo: 'PRJ-002',
    acceptanceCriteria: 'Improve query performance by 30%.',
    taskType: 'Spike',
  },
  {
    id: 8,
    title: 'Fix CSS on Mobile',
    status: 'todo',
    createdAt: '2025-07-05T09:30:00.000Z',
    updatedAt: '2025-07-05T09:30:00.000Z',
    description: 'Fix layout Bugs on smaller devices.',
    assignee: 'Anjali Sharma',
    reporter: 'Kiran Patil',
    labels: ['css', 'responsive'],
    order: 8,
    comments: [],
    sprintNo: 'Sprint 2',
    projectNo: 'PRJ-002',
    acceptanceCriteria: 'No horizontal scroll on mobile.',
    taskType: 'Bug',
  },
  {
    id: 9,
    title: 'Set Up CI/CD Pipeline',
    status: 'done',
    createdAt: '2025-07-01T08:00:00.000Z',
    updatedAt: '2025-07-04T15:00:00.000Z',
    description: 'Configure GitHub Actions for test, build, deploy.',
    assignee: 'Prasant Mahato',
    reporter: 'Rahul Mehta',
    labels: ['ci', 'deployment'],
    order: 9,
    comments: [{ text: 'Add secret keys in GitHub settings.', time: '2025-07-04T15:15:00.000Z' }],
    sprintNo: 'Sprint 1',
    projectNo: 'PRJ-001',
    acceptanceCriteria: 'Automated pipeline on push to main.',
    taskType: 'Ticket',
  },
  {
    id: 10,
    title: 'Create API Documentation',
    status: 'inprogress',
    createdAt: '2025-07-06T12:00:00.000Z',
    updatedAt: '2025-07-06T12:00:00.000Z',
    description: 'Document endpoints in Swagger.',
    assignee: 'Kiran Patil',
    reporter: 'Sneha Raj',
    labels: ['api', 'documentation'],
    order: 10,
    comments: [],
    sprintNo: 'Sprint 2',
    projectNo: 'PRJ-002',
    acceptanceCriteria: 'Swagger doc must include all current APIs.',
    taskType: 'Spike',
  }
];
